# Generated by Django 4.0.4 on 2022-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Indica el título del libro', max_length=32)),
                ('summary', models.TextField(help_text='Indica sobre que trata el libro', max_length=100)),
            ],
        ),
    ]
