# Generated by Django 4.0.4 on 2022-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gener',
            field=models.ManyToManyField(to='catalog.genre'),
        ),
    ]
