# Generated by Django 4.0.4 on 2022-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=1111111111111, help_text='Indica el ISBN de 13 caracteres', max_length=13, verbose_name='ISBN'),
            preserve_default=False,
        ),
    ]
